{
 "title": "Global Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "VM CPU System Load (1m avg) (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1 +on(instance) group_left(nodename) (node_uname_info - 1)) by (nodename) / count(count(node_cpu_seconds_total +on(instance) group_left(nodename) node_uname_info) by (nodename, cpu)) by (nodename) * 100",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "VM RAM Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (((node_memory_MemAvailable_bytes +on(instance) group_left(nodename) node_uname_info) * 100) / (node_memory_MemTotal_bytes +on(instance) group_left(nodename) node_uname_info))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "VM FS Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "repeat": "name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (((node_filesystem_avail_bytes{mountpoint=\"/\", fstype=\"ext4\"} +on(instance) group_left(nodename) node_uname_info) * 100) / (node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\"} +on(instance) group_left(nodename) node_uname_info))",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}