- hosts: all
#- hosts: lfn-poc
  become: yes
  tasks:
  - name: remove old docker (as 1.12) if installed
    apt:
      name: docker-engine
      state: absent
      purge: true

  - name: remove recent docker (as 17.03.2) if installed
    apt:
      name: docker-ce
      state: absent
      purge: true

  - name: update
    apt:
      update_cache: yes

  - name: upgrade all
    apt:
      name: "*"
      state: latest
      force_apt_get: yes

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: Set understandable hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Unconditionally reboot the machine with all defaults
    reboot:

  - name: Add docker Apt signing key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  
  - apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: update
    apt:
      update_cache: yes 

  - name: Install docker 19.03.5
    apt:
      name: docker-ce=5:19.03.5~3-0~ubuntu-bionic
      force_apt_get: yes
      state: present

  - name: apt-mark hold docker-ce
    shell: apt-mark hold docker-ce

  - name: Add user ubuntu to group docker
    shell: usermod -aG docker ubuntu
